name: Update Chart Metadata

on: push

jobs:
  update-chart-metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        git-push: true
